### PR TITLE
[0.4.x] lv-tool: Always skip actors "gstreamer" and "gdkpixbuf" when cycling

### PR DESCRIPTION
**Pull request by hartwork**
Inspired by https://github.com/hartwork/xmms2-devel/blob/2b8cc16791aceaf6ff121418041f1f6ae9f99c86/src/clients/vistest/libvisual.c#L142 .

### CODE REVIEW

**Review by kaixiong — COMMENTED** [review]
@hartwork Good idea! I'm thinking that we should generalise this slightly by using an array of actors to skip.

**Comment by hartwork** [comment]
> @hartwork Good idea! I'm thinking that we should generalise this slightly by using an array of actors to skip.

@kaixiong no objections in general, but before I have brushed up on C++ more this will take me more time than it adds practical value, at least today, and I can bring more value to other pull requests with plain C using that same time. Would you mind taking over this C++ refactoring?

**Comment by kaixiong** [comment]
> @kaixiong no objections in general, but before I have brushed up on C++ more this will take me more time than it adds practical value, at least today, and I can bring more value to other pull requests with plain C using that same time. Would you mind taking over this C++ refactoring?

@hartwork. Yup, I can do it. Let's proceed with this then. The PR queue is getting long :)

**Review by kaixiong — APPROVED** [review]

**Comment by hartwork** [comment]
@kaixiong thank you! :+1:

**Pull request merged**
