### PR TITLE
libvisual-plugins: Fix mplayer input plugin

### PR DESCRIPTION
**Pull request by hartwork**
Similar to pull request #158 but for `master`.

### CODE REVIEW

**Review by kaixiong — COMMENTED** [review]
Nice fix. A few points:

- I'm not entirely comfortable with setting an unsigned integral type to `-1` even though the C standard seems to guarantee the wrap around. Perhaps assigning `ULLONG_MAX` (from C99's `<limits.h>`) would be better.
- Do you know if MPlayer is guaranteed to produce a new and complete 'frame' each time we read from the mmap'ed block (assuming that the counter changes)?

**Comment by hartwork** [comment]
> Nice fix. A few points:
> 
> * I'm not entirely comfortable with setting an unsigned integral type to `-1` even though the C standard seems to guarantee the wrap around. Perhaps assigning `ULLONG_MAX` (from C99's `<limits.h>`) would be better.

I don't share the concern (and an explicit cast would be an option) but I have adjust it as suggested.


> * Do you know if MPlayer is guaranteed to produce a new and complete 'frame' each time we read from the mmap'ed block (assuming that the counter changes)?

I believe it's full 512 frames every time. If it's not, the interface has no field of telling the count. The man page says this:

> ```
>        export[=mmapped_file[:nsamples]]
>               Exports the incoming signal to other processes using memory mapping (mmap()).  Memory mapped areas contain a header:
> 
>               int nch                      /*number of channels*/
>               int size                     /*buffer size*/
>               unsigned long long counter   /*Used to keep sync, updated every
>                                              time new data is exported.*/
> 
>               The rest is payload (non-interleaved) 16 bit data.
>                  <mmapped_file>
>                       file to map data to (default: ~/.mplayer/mplayer-af_export)
>                  <nsamples>
>                       number of samples per channel (default: 512)
> 
>               EXAMPLE:
>                  mplayer -af export=/tmp/mplayer-af_export:1024 media.avi
>                       Would export 1024 samples per channel to '/tmp/mplayer-af_export'.
> ```

What strikes me as odd right now is the "non(!)-interleaved" in there :thinking: When testing with https://www.kozco.com/tech/LRMonoPhase4.wav and `mplayer -af export LRMonoPhase4.wav` locally the data seems interleaved rather than non-interleaved to me.

**Comment by hartwork** [comment]
@kaixiong PS: I just "verified" that at least in my local experiments `int size` is the same value (2048) every time.

**Review by kaixiong — APPROVED** [review]
Looks good!

**Pull request merged**
