### PR TITLE
lv_cpu: Use Rip if on 64-bit Windows

### LINKED ISSUE #77: [0.4.0] Compilation error on Windows 64 bits
on 32 bits, Eip register is used while Rip should be used on 64 bits

see https://github.com/Libvisual/libvisual/blob/master/libvisual/libvisual/lv_cpu.c#L136

### PR DESCRIPTION
**Pull request by 1480c1**
Fixes #77

### CODE REVIEW

**Comment by 1480c1** [comment]
I can try to add a mingw-w64 it msvc build to appveyor or GitHub actions to accompany this pr

**Comment by hartwork** [comment]
Is this `->Rip` versus `->Eip` something that produces compile errors in the wrongly bit-counted version of Windows? #77 is rather vague about it and — while Windows CI using GitHub Actions or AppVeyor would be a great way forward — we'll still need speictic test code or compile errors for them to catch issues. Am I missing something?

**Comment by 1480c1** [comment]
> Is this `->Rip` versus `->Eip` something that produces compile errors on the wrongly bit-counted version of Windows? #77 is rather vague about it and — while Windows CI using GitHub Actions or AppVeyor would be a great way forward — we'll still need specific test code or compile errors for them to catch issues. Am I missing something?

Currently, on mingw-w64
```bash
D:/msys64/home/cddeg/libvisual/libvisual/libvisual/private/lv_video_blit_simd.cpp: In static member function 'static void LV::VideoBlit::blit_overlay_alphasrc_mmx(LV::Video*, LV::Video*)':
D:/msys64/home/cddeg/libvisual/libvisual/libvisual/private/lv_video_blit_simd.cpp:32:53: warning: unused parameter 'dest' [-Wunused-parameter]
   32 |   void VideoBlit::blit_overlay_alphasrc_mmx (Video* dest, Video* src)
      |                                              ~~~~~~~^~~~
D:/msys64/home/cddeg/libvisual/libvisual/libvisual/private/lv_video_blit_simd.cpp:32:66: warning: unused parameter 'src' [-Wunused-parameter]
   32 |   void VideoBlit::blit_overlay_alphasrc_mmx (Video* dest, Video* src)
      |                                                           ~~~~~~~^~~
D:/msys64/home/cddeg/libvisual/libvisual/libvisual/private/lv_video_scale_simd.cpp: In static member function 'static void LV::VideoTransform::scale_bilinear_color32_mmx(LV::Video&, const LV::Video&)':
D:/msys64/home/cddeg/libvisual/libvisual/libvisual/private/lv_video_scale_simd.cpp:31:59: warning: unused parameter 'dst' [-Wunused-parameter]
   31 |   void VideoTransform::scale_bilinear_color32_mmx (Video& dst, Video const& src)
      |                                                    ~~~~~~~^~~
D:/msys64/home/cddeg/libvisual/libvisual/libvisual/private/lv_video_scale_simd.cpp:31:77: warning: unused parameter 'src' [-Wunused-parameter]
   31 |   void VideoTransform::scale_bilinear_color32_mmx (Video& dst, Video const& src)
      |                                                                ~~~~~~~~~~~~~^~~
D:/msys64/home/cddeg/libvisual/libvisual/libvisual/lv_cpu.c: In function 'win32_sig_handler_sse':
D:/msys64/home/cddeg/libvisual/libvisual/libvisual/lv_cpu.c:136:22: error: 'struct _CONTEXT' has no member named 'Eip'; did you mean 'Rip'?
  136 |   ep->ContextRecord->Eip +=3;
      |                      ^~~
      |                      Rip
make[2]: *** [libvisual/CMakeFiles/libvisual.dir/build.make:128: libvisual/CMakeFiles/libvisual.dir/lv_cpu.c.obj] Error 1
make[2]: *** Waiting for unfinished jobs....
D:/msys64/home/cddeg/libvisual/libvisual/libvisual/private/windows/lv_time_system.cpp: In function 'LV::Time LV::TimeSystem::now()':
D:/msys64/home/cddeg/libvisual/libvisual/libvisual/private/windows/lv_time_system.cpp:37:45: warning: narrowing conversion of '(((long long unsigned int)perf_counter._LARGE_INTEGER::QuadPart) / LV::TimeSystem::counter_freq)' from 'long long unsigned int' to 'long int' [-Wnarrowing]
   37 |         return Time { perf_counter.QuadPart / counter_freq,
      |                       ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
D:/msys64/home/cddeg/libvisual/libvisual/libvisual/private/windows/lv_time_system.cpp:38:87: warning: narrowing conversion of '(((((long long unsigned int)perf_counter._LARGE_INTEGER::QuadPart) % LV::TimeSystem::counter_freq) * 1000000000) / LV::TimeSystem::counter_freq)' from 'long long unsigned int' to 'long int' [-Wnarrowing]
   38 |                       ((perf_counter.QuadPart % counter_freq) * VISUAL_NSECS_PER_SEC) / counter_freq };
      |                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
make[2]: Leaving directory '/home/cddeg/libvisual/libvisual/build'
make[1]: *** [CMakeFiles/Makefile2:617: libvisual/CMakeFiles/libvisual.dir/all] Error 2
make[1]: Leaving directory '/home/cddeg/libvisual/libvisual/build'
make: *** [Makefile:152: all] Error 2
```

**Comment by stuaxo** [comment]
+1 on CI :)

**Comment by hartwork** [comment]
@1480c1 thanks for the build output!

A few thoughts:
- Is `_AMD64_` the right/best guard macro to use? [Is `_WIN64`](https://sourceforge.net/p/predef/wiki/OperatingSystems/)?
- Is 3 the right value for Rip as well?
- I found this code/comment that seems to be strongly related to what we're about to change, except on Linux: https://github.com/Libvisual/libvisual/blob/4366db14a1f2a1f76932353a25d8a06920417354/libvisual/libvisual/lv_cpu.c#L97-L115
- Is this Rip-vs-Eip thing a Windows-only topic?

**Comment by 1480c1** [comment]
> * Is `_AMD64_` the right/best guard macro to use? [Is `_WIN64`](https://sourceforge.net/p/predef/wiki/OperatingSystems/)?

Perhaps not, but that's the macro I kept on seeing in window's own headers instead of `_WIN64`



> * Is 3 the right value for Rip as well?

I'm not sure if this is correct since I haven't necessarily modified code related to this before, I can do some more research to see


> * I found this code/comment that seems to be strongly related to what we're about to change, except on Linux:

Same reply as above



> * Is this Rip-vs-Eip thing a Windows-only topic?

afaik, yes

**Pull request merged**
