### PR TITLE
Core (Memory): Remove custom implementations of memset() and memcpy().

### LINKED ISSUE #275: Throw out SIMD versions of memcpy and memset?
[lv_mem.c](https://github.com/Libvisual/libvisual/blob/master/libvisual/libvisual/lv_mem.c) has a bunch of x86/x64 SIMD versions of `memset` and `memcpy`. I believe glibc already does so when it's able to and is far more portable.

On top of that, I've noticed playing a bit on Godbolt that GCC even recognises a naive C/C++ implementation of `memcpy` and reduces it to a call to `memcpy` when `restrict` is used! So it's time to re-evaluate and hopefully ditch all the custom code.

### PR DESCRIPTION
**Pull request by kaixiong**
This closes #275.

### CODE REVIEW

**Review by hartwork — APPROVED** [review]
@kaixiong if you think this is the right move for GCC, Clang and MSVC, I'll trust your evaluation that it's a good move.

**Comment by kaixiong** [comment]
@hartwork, thanks! Before merging, I'll be writing some benchmarks just to be sure.

**Comment by kaixiong** [comment]
@hartwork  So, I did some benchmarks on my Ryzen 3800X and the conclusion is that `memset` and `memcpy` in GLIBC 2.35 are way faster.

The custom implementation of `memset` only managed to beat GLIBC when the buffer size gets very, very large.

```
Benchmarking setting of 100-byte buffers for 30000000 times.
Libc  : 0.068742536
Custom: 2.4781213s
Libc   (align:64): 0.062081587s
Custom (align:64): 2.4186823s

Benchmarking setting of 1000-byte buffers for 3000000 times.
Libc  : 0.028145673
Custom: 0.7951929s
Libc   (align:64): 0.025319144s
Custom (align:64): 0.25986797s

Benchmarking setting of 10000-byte buffers for 300000 times.
Libc  : 0.021937693
Custom: 0.17037342s
Libc   (align:64): 0.021939714s
Custom (align:64): 0.11822792s

Benchmarking setting of 100000-byte buffers for 30000 times.
Libc  : 0.022369063
Custom: 0.12401633s
Libc   (align:64): 0.022298902s
Custom (align:64): 0.12001014s

Benchmarking setting of 1000000-byte buffers for 3000 times.
Libc  : 0.0313901
Custom: 0.11938574s
Libc   (align:64): 0.031296194s
Custom (align:64): 0.12024417s

Benchmarking setting of 10000000-byte buffers for 300 times.
Libc  : 0.038335808
Custom: 0.11929301s
Libc   (align:64): 0.040508896s
Custom (align:64): 0.1192395s

Benchmarking setting of 100000000-byte buffers for 30 times.
Libc  : 0.18999872
Custom: 0.11893117s
Libc   (align:64): 0.19158955s
Custom (align:64): 0.11915644s

Benchmarking setting of 1000000000-byte buffers for 3 times.
Libc  : 0.18418951
Custom: 0.11886752s
Libc   (align:64): 0.18664192s
Custom (align:64): 0.11876087s
```
```
Benchmarking copying of 100-byte buffers for 30000000 times.
Libc  : 0.06925089s
Custom: 6.7890935s
Libc   (align:64): 0.0763941s
Custom (align:64): 2.4200647s

Benchmarking copying of 1000-byte buffers for 3000000 times.
Libc  : 0.027088974s
Custom: 0.8125392s
Libc   (align:64): 0.026974056s
Custom (align:64): 0.2559263s

Benchmarking copying of 10000-byte buffers for 300000 times.
Libc  : 0.022581017s
Custom: 0.11892752s
Libc   (align:64): 0.022397308s
Custom (align:64): 0.11890911s

Benchmarking copying of 100000-byte buffers for 30000 times.
Libc  : 0.046463612s
Custom: 0.124137245s
Libc   (align:64): 0.042351864s
Custom (align:64): 0.11862049s

Benchmarking copying of 1000000-byte buffers for 3000 times.
Libc  : 0.058072977s
Custom: 0.11854469s
Libc   (align:64): 0.058297176s
Custom (align:64): 0.118819505s

Benchmarking copying of 10000000-byte buffers for 300 times.
Libc  : 0.18565437s
Custom: 0.12066272s
Libc   (align:64): 0.18945421s
Custom (align:64): 0.12163156s

Benchmarking copying of 100000000-byte buffers for 30 times.
Libc  : 0.1617569s
Custom: 0.17586423s
Libc   (align:64): 0.16233315s
Custom (align:64): 0.17589606s

Benchmarking copying of 1000000000-byte buffers for 3 times.
Libc  : 0.15747143s
Custom: 0.16953292s
Libc   (align:64): 0.16081342s
Custom (align:64): 0.17009889s
```

**Comment by hartwork** [comment]
@kaixiong thanks for going this mile! :+1:

**Comment by dsmit** [comment]
What a difference compared to 15 years ago!

**Comment by kaixiong** [comment]
> What a difference compared to 15 years ago!

@dsmit, indeed!

I tried some relatively simple SSE2 implementations ([link](https://gist.github.com/kaixiong/be0ba18e70181c18c621298e6053cf73)) using `_mm_storeu_si128` and could only get around 50%-80% the speed of glibc's versions for <16MB buffers. It's clear that glibc is pretty well optimized here.

**Pull request merged**
